version: "3"

services:
  wordpress:
    image: wordpress:5.7-php7.4
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
#Inicio Nueva Linea proyectos
      - ${PWD}/temas/ElInformador:/var/www/html/wp-content/themes/ElInformador #Tema ya creado solo lo cargo para verificar funcionamiento
      - ${PWD}/temas/DevWP:/var/www/html/wp-content/themes/DevWP #Tema para desarrollo este es en el que voy a trabajar
     # - ${PWD}/temas/SUITE_ADOBE.zip:/var/www/html/wp-content/themes/suite.zip #Test
#Fin Nueva Linea proyectos
#Inicio para almacenar plugins fuera del contenedor
      - ${PWD}/plugins/:/var/www/html/wp-content/plugins/
#Fin
#Inicio para almacenar archivos multimedia
      - ${PWD}/multimedia:/var/www/html/wp-content/uploads
#Fin
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      #- mysql:/var/lib/mysql
      - ./db:/var/lib/mysql #almacenando los datos fuera del contenedor

volumes:
  wordpress:
  mysql:
